### ISSUE TITLE
https://www.nodebb.org (as opposed to https://nodebb.org ) will show TLS error / invalid cert after connecting

### ISSUE THREAD

**Issue by ghost** [NodeBB/nodebb.org#13]
https://www.nodebb.org (as opposed to https://nodebb.org ) will show TLS error / invalid cert after connecting, and the error indicates this subdomain isn't covered by the certificate the webserver uses. Since some people still expect www. to work and it's most notably also linked like that from @julianlam 's profile, I suggest that this certificate issue is fixed.

**Comment by julianlam** [comment]
:+1:

**Comment by julianlam** [comment]
Resolved. Seems when I switched over to Let's Encrypt, I only passed in `-d nodebb.org -d nodebb.com` in. Silly me.

**Comment by ghost** [comment]
Yup it appears to be working correctly now. :heart:
